# vim ft=yaml
# travis-ci.org definition for DataLad build
language: python

cache:
  - apt

python:
  - "2.7"
  - "3.3"
  - "3.4"
# not there -- don't try!
# - "3.5"
# can't since coverage doesn't support it yet: https://bitbucket.org/ned/coveragepy/issues/391/getargspec-was-finally-removed-will-not-be
#  - "nightly"

before_install:
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get update -qq

install:
  # Install standalone build of git-annex for the recent enough version
  - sudo apt-get install git-annex-standalone zip
  - git config --global user.email "test@travis.land"
  - git config --global user.name "Travis Almighty"
  - git submodule update --init --recursive
  - cd ..; pip install -q coveralls; cd -
  - pip install -r requirements.txt
  - pip install -e .

script:
  - DATALAD_LOGLEVEL=INFO nosetests -v --with-doctest --with-cov --cover-package datalad --logging-level=INFO --failed

after_success:
  - coveralls

after_failure:
  - DATALAD_LOGLEVEL=DEBUG nosetests -s -v --with-doctest --with-cov --cover-package datalad --logging-level=DEBUG --failed
