name: Test on macOS

on:
    - pull_request
    - push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Set up system
      shell: bash
      run: |
        brew install git-annex

    - name: Set up environment
      run: |
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"

    - uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: WTF!?
      run: |
        datalad wtf

    - name: Run tests
      run: |
        mkdir -p __testhome__
        cd __testhome__
        python -m nose -s -v datalad.core datalad.support
